@startuml
title Приклад діаграми активності

start

:Система аналізує рівень освітленості;

if (Отримано рівень освітленості?) then (так)
  :Надсилання інформації про рівень освітленості;
  stop
else (ні)
  :Помилка підключення;
  stop
endif

@enduml
