@startuml
!theme mars

title Use Case для Інформаційної системи

left to right direction

actor Користувач
actor :LightControlSystem:

rectangle Software {

    usecase (Вхід в систему)
    usecase (Перегляд інформації про рівень освітленості)
    usecase (Надання рекомендацій щодо оптимального освітлення)
    usecase (Спілкування з іншими користувачами)
    usecase (Перегляд інформації про оптимальні рекомендації для зорового комфорту)

   :LightControlSystem: -- (Перегляд інформації про рівень освітленості)
   (Вхід в систему) .> (Перегляд інформації про рівень освітленості) : include
   (Надання рекомендацій щодо оптимального освітлення) .> (Перегляд інформації про рівень освітленості) : include
   Користувач -- (Вхід в систему)
   Користувач -- (Перегляд інформації про рівень освітленості1)
   Користувач -- (Спілкування з іншими користувачами)
   Користувач -- (Надання рекомендацій щодо оптимального освітлення)
   Користувач -- (Перегляд інформації про оптимальні рекомендації для зорового комфорту)
}
@enduml
